package ExportToNeo4j.behavior;

/*Generated by MPS */

import jetbrains.mps.project.MPSProject;
import com.intellij.openapi.project.Project;
import jetbrains.mps.workbench.MPSDataKeys;
import com.intellij.ide.DataManager;
import jetbrains.mps.ide.project.ProjectHelper;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class Helper {
  public static class Neo4j {
    public static MPSProject getMPSProject() {
      Project ideaproject = MPSDataKeys.PROJECT.getData(DataManager.getInstance().getDataContext());
      return ProjectHelper.fromIdeaProject(ideaproject);
    }
    public static boolean SModuleIsInProject(SModule sModule) {
      for (SModule ModuleInProject : ListSequence.fromList(Neo4j.getMPSProject().getProjectModules())) {
        if (sModule == ModuleInProject) {
          return true;
        }
      }
      return false;
    }
    public static SModule getSModule(String name) {
      for (SModule Mod : ListSequence.fromList(Neo4j.getMPSProject().getProjectModules())) {
        if (name.equals(Mod.getModuleName())) {
          return Mod;
        }
      }
      return null;
    }
  }
}
