package ExportToNeo4j.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ExportToNeo4j = 0;
  public static final int Module = 1;
  public static final int ModuleReference = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x51b96d8c96c640cfL, 0x9e04d484a4ac7485L);
    builder.put(0x68c3cf50b4415fcfL, ExportToNeo4j);
    builder.put(0x68c3cf50b4430210L, Module);
    builder.put(0x68c3cf50b4430249L, ModuleReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
