package lang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int conceptA = 0;
  public static final int conceptB = 1;
  public static final int rootConcept = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x8ef710002c5f42a8L, 0xa49b6e266ef0e636L);
    builder.put(0x98b8c4b9650d52cL, conceptA);
    builder.put(0x98b8c4b9650d52dL, conceptB);
    builder.put(0x98b8c4b9650d52bL, rootConcept);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
